### ISSUE TITLE
Scale is too low in Mac condition.

### ISSUE THREAD

**Issue by datsu28** [roychowdhuryresearch/pyHFO#4]
Hi, I am working on an Mac OS Monterey 12.6
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)

When I run pyHFO, the scaling is weird an it is difficult to see the amplitude because it is too much scaled in too much low amplitude.

Furthermore, the size of annotation window is fixed and I can not get rid of the overlapped letter and window for visual demonstration.For instance, it is difficult to see PSD here.

Thank you very much for your consideration.

<img width="945" alt="Screen Shot 2024-06-30 at 2 16 24 PM" src="https://github.com/roychowdhuryresearch/pyHFO/assets/125303091/de34673d-b1e3-4a59-b109-aa2334ed5071">
<img width="865" alt="Screen Shot 2024-06-30 at 2 16 01 PM" src="https://github.com/roychowdhuryresearch/pyHFO/assets/125303091/94437a03-6f37-4708-844b-45c54bf6b2fb">

**Comment by zyp5511** [comment]
This has been fixed in the release
